### ISSUE TITLE
Ask for confirmation before applying dangerous commands

### ISSUE THREAD

**Issue by lucasbrunialti** [Cobliteam/cassandra-migrate#19]

**Comment by Fedorsturov** [comment]
Which commands are deemed dangerous? Just askin' :wink:

**Comment by lucasbrunialti** [comment]
- `reset` is a really dangerous command
- `migrate` if it will apply something

**Comment by danielkza** [comment]
My idae is to show a prompt if we're running interactively (if stdin is a TTY), and to provide a `--yes` option that always skips checks.

**Comment by danielkza** [comment]
Fixed by #21.
