### ISSUE TITLE
Support Python migrations (instead of just CQL)

### ISSUE THREAD

**Issue by lucasbrunialti** [Cobliteam/cassandra-migrate#20]

**Comment by ppcuban** [comment]
We are working into implementing python migrations in our fork. We have some questions that maybe you already have answered. 

For example, right now the code is looking for '*.cql' exclusively in the migrations folder. We were debating wether we want any migration script (.cql or .py) to run simultaneously based on filename ordering OR explicitly set which type of file would run at a time, or both on demand.

**Comment by danielkza** [comment]
This has actually been supported for a while.
