### ISSUE TITLE
Migration prefix without collission

### ISSUE THREAD

**Issue by holgerw** [Cobliteam/cassandra-migrate#3]
Thank's for your great tool.

In a team environment there might be collisions on the version prefix as it is a sequential number. Imagine 2 people evolving the schema, pulling the other's source updates only with some delay. This simultaneous work on the schema is very well possible, if each focuses on distinct tables

But with the sequential version prefix, both would generate migration files with the same prefix, right?

I would like suggest a timestamp as the prefix, as with Rails Migrations.

**Comment by danielkza** [comment]
That is a very sensible request, I'll implemented it whenever I can. (a PR is also very welcome, of course :) )

**Comment by danielkza** [comment]
Should be fixed by c6134fc991c9624a5b4cb53e2d2cd7af9338f20d.

@holgerw Can you please test the new 0.2.1 version and see if it works for you? The README includes docs on how to customize the migration names.

**Comment by holgerw** [comment]
@danielkza version 0.2.2 works perfectly for me, with timestamp prefixed migration names. Thanks for implementing these new configuration options.

**Comment by danielkza** [comment]
@holgerw That's great to know, specially helping some fellow Brazilians. Thank you for the feedback!
