### ISSUE TITLE
How to recover from a failed migration?

### ISSUE THREAD

**Issue by pdehlke** [Cobliteam/cassandra-migrate#30]
So I'm looking at this package as a way to manage my schema changes. Seems to work quite well, until a migration fails, at which point it's unclear how to recover.

I deliberately created a migration that was intended to fail: it contained a list of 10 ALTER statements, one of which specified a table that does not exist. cassandra-migrate correctly failed to apply the migration:

> 
> The migrate operation cannot be undone. Are you sure? [y/N] y
> INFO:Migrator:Pending migrations found. Current version: 2, Latest version: 3
> INFO:Migrator:Advancing to version 3
> INFO:Migrator:Writing in-progress migration version 3: Migration("v3_US2704_Compaction_Strategies.cql")
> INFO:Migrator:Applying cql migration
> INFO:Migrator:Executing migration with 165 CQL statements
> ERROR:Migrator:Failed to execute migration
> Traceback (most recent call last):
>   File "/Library/Python/2.7/site-packages/cassandra_migrate/migrator.py", line 408, in _apply_cql_migration
>     self.session.execute(statement)
>   File "cassandra/cluster.py", line 2122, in cassandra.cluster.Session.execute
>     return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state).result()
>   File "cassandra/cluster.py", line 3982, in cassandra.cluster.ResponseFuture.result
>     raise self._final_exception
> InvalidRequest: Error from server: code=2200 [Invalid query] message="unconfigured table attribute_type_values"
> ERROR:Migrator:Failed to execute migration
> Traceback (most recent call last):
>   File "/Library/Python/2.7/site-packages/cassandra_migrate/migrator.py", line 454, in _apply_migration
>     self._apply_cql_migration(version, migration)
>   File "/Library/Python/2.7/site-packages/cassandra_migrate/migrator.py", line 411, in _apply_cql_migration
>     raise FailedMigration(version, migration.name)
> FailedMigration: Migration failed, cannot continue (version 3): v3_US2704_Compaction_Strategies.cql
> INFO:Migrator:Finalizing migration version with state FAILED
> Error: Migration failed, cannot continue (version 3): v3_US2704_Compaction_Strategies.cql
> 

I then changed the v3_US2704_Compaction_Strategies.cql and removed the call to ALTER the unconfigured table and attempted to re-run:

> Keyspace:            fubar
> Migrations table:    database_migrations
> Current DB version:  2
> Latest DB version:   3
> 
>  Applied migrations
> 
>     Name                                 State      Date applied               Checksum
> ---  -----------------------------------  ---------  -------------------------  ----------------------------------------------------------------
>   1  v1_First_commit.cql                  SUCCEEDED  2018-01-27 16:05:45+00:00  590a0967af38b59df14151e08d74817c5fa0d170b1db8efb7bf7378334d54281
>   2  v2_Second_commit.cql                 SUCCEEDED  2018-01-27 16:07:32+00:00  d12fbceede8af85cb29d6a8225d955998bb0faac65112138c4bfbe54caa0daeb
>   3  v3_US2704_Compaction_Strategies.cql  FAILED     2018-01-27 16:28:12+00:00  66592f5e47ea87222e1f0134afe9bbf1c907cdcb0de0e8d7e66f59707dbfdc1e
> 
>  Pending migrations
> 
>     Name                                 Checksum
> ---  -----------------------------------  ----------------------------------------------------------------
>   3  v3_US2704_Compaction_Strategies.cql  29eb0f74fdb746e3d3f4bf4aef02e20498038cfdae28b505b1b8d21e6590719b

> pde@Clarence:~/src/cassandra-migrate (master●●)$ cassandra-migrate migrate
> WARNING:cassandra.cluster:Cluster.__init__ called with contact_points specified, but no load_balancing_policy. In the next major version, this will raise an error; please specify a load-balancing policy. (contact_points = [u'127.0.0.1'], lbp = None)
> The migrate operation cannot be undone. Are you sure? [y/N] y
> Error: Migration failed, cannot continue (version 3): v3_US2704_Compaction_Strategies.cql

I then created a v4 migration, which again refuses to apply because v3 has failed.

So: if fixing the syntax of a failed migration file doesn't allow you to get past the failed migration, and subsequent migrations won't apply, how does one fix a failed migration so that work can continue? Am I expected to `reset` and then completely repopulate my dev cluster if I typo a migration file?

**Comment by danielkza** [comment]
@pdehlke After fixing a broken migration, you can re-run cassandra-migrate with the `--force` flag.

**Comment by pdehlke** [comment]
Roger that. Thanks! Closing.
