### ISSUE TITLE
NetworkTopologyStrategy

### ISSUE THREAD

**Issue by penchalgaddam** [Cobliteam/cassandra-migrate#35]
Hi ,

Will this yml supports NetworkTopologyStrategy like below?

keyspace: migrate1_test
profiles:
   migrate1_test
    replication:
      class: NetworkTopologyStrategy
      DC1: 3
      DC2: 3
migrations_path: ./migrations

Thanks

**Comment by danielkza** [comment]
Whatever is passed in the `replication` dictionary is converted to a CQL literal and passed through to Cassandra, so any replication strategy should work. Just make sure your indentation is right (as it was lost while pasting the comment). Please reopen this issue if you find any issue with that functionality.
