### ISSUE TITLE
Password with $

### ISSUE THREAD

**Issue by penchalgaddam** [Cobliteam/cassandra-migrate#36]
Hi,

When my password is with $ sign, it throughs code=0100 [Bad credentials], any idea how to overcome it?

Thanks

**Comment by danielkza** [comment]
cassandra-migrate reads the password from the command line and passes it directly to the Cassandra driver authentication provider. Please check if you are quoting the password correctly when *calling* the command: you need to wrap it in single (`'`) or double (`"`) quotes so your shell does not interpret the `$` as the beginning of a variable expansion.

**Comment by penchalgaddam** [comment]
Thank you.
