### ISSUE TITLE
why cassandra-migrate installation take about 5m?

### ISSUE THREAD

**Issue by msudgh** [Cobliteam/cassandra-migrate#42]
I'm trying to install `cassandra-migrate` by `pip -vv` flag and I've figured out, it tries to build `cassandra-driver` by `gcc`. why its slow, isnt there alternative to make it faster?

**Comment by danielkza** [comment]
Set the `CASS_DRIVER_NO_CYTHON=1` environment variable and it should be
much faster.

Em qui, 6 de dez de 2018 08:24, Masoud Ghorbani <notifications@github.com>
escreveu:

**Comment by danielkza** [comment]
Closing as this is a problem with the Cassandra driver, and at the moment there's nothing I can change about it.
