### ISSUE TITLE
Why are the generated v0**.cql files blank except header comment?

### ISSUE THREAD

**Issue by george-world** [Cobliteam/cassandra-migrate#48]
@danielkza 

Thank you for the great project of Cassandra Migration at first.

I'm trying to migrate data of Cassandra@2.1 to cloud service of Cassandra@3.x.

I followed the step below and got blank files of *.cql.
https://github.com/Cobliteam/cassandra-migrate#generate

My question is how to dump all data from KeySpace?

Thanks!

**Comment by gustavo-momente** [comment]
Hello @george-world thanks for taking the time to try this project. Right now `cassandra-migrate` isn't intended to use to migrate data from one Cassandra to another, it's more to evolve Cassandra table schemas.

If you want to move your data from one Cassandra to another, one option is to use the (Python Cassandra driver)[https://docs.datastax.com/en/developer/python-driver/latest] that would allow you to connect to the old instance and move the data to the new Instance.

**Comment by george-world** [comment]
Thanks for your advice! @gustavo-momente （笑）
