### ISSUE TITLE
make a release

### ISSUE THREAD

**Issue by lukasGemela** [Cobliteam/cassandra-migrate#58]
Hello people,

many thanks for the work you're doin. Do you think it would be possible to release latest changes from trunk? We are having dependency issues around pyYAML library:

The conflict is caused by:
    cassandra-migrate 0.3.3 depends on PyYAML<5.0
    pyaml-env 1.1.1 depends on PyYAML==5.4.1

would be cool if we can upgrade to cassandra-migrate 0.3.4 which should solve this problem. Also one pr linked to the issue:

https://github.com/Cobliteam/cassandra-migrate/pull/59

Many thanks!

**Comment by stoiev** [comment]
Thanks for your contribution!

Published in PyPi as cassandra-migrate 0.3.4
