### ISSUE TITLE
Usage of replication_factor > 1

### ISSUE THREAD

**Issue by sierpito** [Cobliteam/cassandra-migrate#8]
Maybe, it isn’t an issue, but misconfiguration or incorrect usage of replication.

cassandra-migrate-abc.yml
```
keyspace: abc
profiles:
  dev:
    replication:
      class: SimpleStrategy
      replication_factor: 2
migrations_path: ./migrations-abc
```
migrations-abc/v001-users.cql 
```
CREATE TABLE abc.users (
    user_id text PRIMARY KEY,
    email text,
    first_name text,
    last_name text,
    phone text,
    roles text,
    status text,
    pwd_salt text,
    pwd_hash text
);
```

```cassandra-migrate -H docker-dev -c cassandra-migrate-abc.yml -m dev migrate```

And result:
```
Traceback (most recent call last):
  File "/usr/local/bin/cassandra-migrate", line 18, in <module>
    main()
  File "/Library/Python/2.7/site-packages/cassandra_migrate/cli.py", line 99, in main
    cmd_method(opts)
  File "/Library/Python/2.7/site-packages/cassandra_migrate/migrator.py", line 461, in migrate
    ignore_failed=opts.force)
  File "/Library/Python/2.7/site-packages/cassandra_migrate/migrator.py", line 263, in _verify_migrations
    'SELECT * FROM "{keyspace}"."{table}"'))
  File "/Library/Python/2.7/site-packages/cassandra_migrate/migrator.py", line 195, in _execute
    return self.session.execute(query, *args, **kwargs)
  File "cassandra/cluster.py", line 2016, in cassandra.cluster.Session.execute (cassandra/cluster.c:35491)
  File "cassandra/cluster.py", line 3826, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:74365)
cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 10.133.0.20 europe-west1>: Unavailable('Error from server: code=1000 [Unavailable exception] message="Cannot achieve consistency level ALL" info={\'required_replicas\': 2, \'alive_replicas\': 1, \'consistency\': \'ALL\'}',)})
```

**Comment by holgerw** [comment]
@sierpito does your Cassandra development cluster consiste of 2+ nodes? I am not 100% sure, but it should be correct for Cassandra to fail with a keyspace creation, if the demanded replication_factor is larger then the number of nodes.

**Comment by sierpito** [comment]
Cassandra development cluster is a local Docker container with a single instance of Cassandra.

With replication factor 2 everything works correctly through cql.
```$ cqlsh -f schema.cql docker-dev```
where first statement is a keyspace definition
```CREATE KEYSPACE IF NOT EXISTS abc
WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 2 };```

And as DataStax documentation states it is a correct case:
http://docs.datastax.com/en/cassandra/3.0/cassandra/architecture/archDataDistributeReplication.html

"SimpleStrategy: Use only for a single datacenter and one rack."
"A replication factor of 2 means two copies of each row, where each copy is on a different node. All replicas are equally important; there is no primary or master replica."
"However, you can increase the replication factor and then add the desired number of nodes later."

**Comment by danielkza** [comment]
@sierpito I see your point, but I believe there is a difference between increasing the replication factor of an existing keyspace, and creating a new keyspace with a replication factor that cannot be satisfied. 

I can make the consistency level that the migrations execute in configurable, but I believe the default must be `ALL`, or at a minimum `EACH_QUORUM`, to reduce the risk of desyncs and schema update timeouts.

Any particular reason you cannot populate the cluster completely before running the migrations?

**Comment by sierpito** [comment]
OK. I agree with you. Your point is that my Docker cluster is incomplete for replication_factor=2 even if it works through cql.

Please explain me if the only way to make success with migrations is either to have dev Docker cluster changes or configure different profiles (yml files) for development and uat/prod? Looks like second option is better.

**Comment by sierpito** [comment]
Thank you. Closed.
